### ISSUE TITLE
signercertificateStatus service returned empty array and signercertificateUpdate 204 No Content

### ISSUE THREAD

**Issue by tdinckaya** [eu-digital-green-certificates/dgca-verifier-service#44]
Hello,

https://dgca-verifier-service.cfapps.eu10.hana.ondemand.com/signercertificateStatus

### This api service return empty array. Why ?

![image](https://user-images.githubusercontent.com/44499170/120190169-e912d680-c220-11eb-831f-72a3e224d46f.png)

https://dgca-verifier-service.cfapps.eu10.hana.ondemand.com/signercertificateUpdate

### This api service return 204 No Content. Why ?

![image](https://user-images.githubusercontent.com/44499170/120190256-034cb480-c221-11eb-8751-3c374e69cedb.png)

**Comment by tdinckaya** [comment]
Is there any progress on the subject? @slaurenz

**Comment by slaurenz** [comment]
Hi @tdinckaya,
sorry for the late response. We are currently working on the problem.
Our analysis found so far, that the connection between the test environment gateway and the verifier-service is corrupted / blocked. This leads to the fact, that the service is not able to download new certificates from the gateway and to verify the existing ones. This is the reason, why it responses with an empty list. We are searching for the root cause and a solution for it. We apologize for the inconvenience.

**Comment by zajdee** [comment]
Hi @slaurenz, is there an existing URL for the production verifier service already?
I wasn't able to find any eHealth docs describing where does the production environment (URL) live.

**Comment by slaurenz** [comment]
Hi,
there is no general verifier service URL for production. Each member state has to provide its own verifier service as backend for the local member state verifier app. These backends are synchronized by the DCC (DGC) Gateway. This implementation here only serves as template implementation.

**Comment by slaurenz** [comment]
Hi @tdinckaya,
the service returns certificates again.  Please verify and close the bug on success.
Regards
Simon

**Comment by zajdee** [comment]
@slaurenz Hi, I may have formulated the question incorrectly. Are you aware of the production URL of the DCC (DGC) gateway? This is the nonexistent information. Thanks.

(Also I've verified that the template endpoints work now, however as I'm not the one who has opened the bug, I can't close it.)

**Comment by tdinckaya** [comment]
Hello @slaurenz,
Thank you and your team. It is working now.

Regards,
Tansel
